library(dplyr)
df1 <- read.table("C:/Users/S226953/OneDrive - University of Texas Southwestern/Desktop/scRNAseq/organised_2024.09.30/PLS_HCVcure_scores_all_cells.txt", header = TRUE, sep = "\t")
df2 <- read.table("C:/Users/S226953/OneDrive - University of Texas Southwestern/Desktop/scRNAseq/organised_2024.09.30/PLS_HCVcure_scores_hepatocytes.txt", header = TRUE, sep = "\t")
merged_df <- full_join(df1, df2, by = "Cell_Barcodes")
head(merged_df)
write.table(merged_df, "C:/Users/S226953/OneDrive - University of Texas Southwestern/Desktop/scRNAseq/organised_2024.09.30/PLS_HCVcure_sig_scores_merged_output.txt", sep = "\t", row.names = FALSE, quote = FALSE)
